const GeoLayout n64_mario_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesHalf_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesClosed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesLeft_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesRight_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesUp_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesUp_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesDown_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_MouthWater_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_MouthWater_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_MourhO_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_MourhO_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead),
			GEO_BRANCH(1, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt10),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt11),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesHalf_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesClosed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesLeft_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesRight_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesUp_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesUp_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_EyesDown_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_MouthWater_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_MouthWater_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_MourhO_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_MourhO_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt1),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt2),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt3),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt4),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt5),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt6),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt10),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt1_Capless_Head_Eye_State_Switch_opt11),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesHalf_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesClosed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesLeft_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesRight_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesUp_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesUp_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesDown_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_MouthWater_7),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_MouthWater_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_MourhO_8),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_MourhO_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Torso_skinned_mesh_layer_1),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 1, 0, n64_mario_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 7, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt1),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt2),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt3),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt4),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt5),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt6),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Head_Dead),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Head_Half_Closed),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Head_Closed),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt10),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_Capless_Switch_opt0_Eye_State_Switch_opt11),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, 80, -18, 29, -135),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, -80, 18, -29, -135),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 63, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Forearm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, n64_mario_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Left_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, -63, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Forearm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, n64_mario_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Open),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Peace),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Cap),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1_jump_n64_mario_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 49, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, n64_mario_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 95, 0, 0, n64_mario_Left_Shoe_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Shoe_mesh_layer_5),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, -49, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Leg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, n64_mario_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Shoe_DL_mesh_layer_1),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Shoe_DL_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_5_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Torso_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 1, 0, n64_mario_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 7, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_Metal__METAL__0),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Head_Dead),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Head_Half_Closed),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Head_Closed),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, 80, -18, 29, -135),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, -80, 18, -29, -135),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 63, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, n64_mario_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Left_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, -63, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, n64_mario_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Open),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Peace),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Cap),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2_jump_n64_mario_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 49, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, n64_mario_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, n64_mario_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Shoe_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, -49, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, n64_mario_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Shoe_DL_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Dead_Switch_Option_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Half_Closed_Switch_Option_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_Closed_Switch_Option_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed_Switch_Option_Capless_Head_Half_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed_Switch_Option_Capless_Head_Closed_mesh_layer_5_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Capless_Head_Switch_Option_Capless_Head_mesh_layer_5_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Dead),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Half_Closed),
			GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head_jump_n64_mario_Capless_Head_Switch_Option_Capless_Head_Closed),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_5_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_5_mat_override_Metal__METAL__0),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Torso_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 1, 0, n64_mario_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 7, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_Metal__METAL__0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Head_Dead),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Head_Half_Closed),
											GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Head_Closed),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Capless_Head),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, 80, -18, 29, -135),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, -80, 18, -29, -135),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 63, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, n64_mario_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Left_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, -63, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Forearm_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 61, 0, 0, n64_mario_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_FORCE, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Open),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Peace),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Cap),
										GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3_jump_n64_mario_Right_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 49, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, n64_mario_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 95, 0, 0, n64_mario_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Shoe_mesh_layer_5_mat_override_Metal__METAL__0),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, -49, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, n64_mario_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Leg_skinned_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, n64_mario_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Shoe_DL_mesh_layer_5_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesHalf_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesHalf_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesClosed_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesClosed_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesLeft_3),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesLeft_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesRight_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesRight_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesUp_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesUp_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_EyesDown_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_EyesDown_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt10[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_MouthWater_7),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_MouthWater_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt11[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5_mat_override_MourhO_8),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1_mat_override_MourhO_8),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout n64_mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Torso_skinned_mesh_layer_1),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 1, 0, n64_mario_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 101, 7, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Head_DL_mesh_layer_5),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Head_DL_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt1),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt2),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt3),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt4),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt5),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt6),
																	GEO_BRANCH(1, n64_mario_Head_Dead),
																	GEO_BRANCH(1, n64_mario_Head_Half_Closed),
																	GEO_BRANCH(1, n64_mario_Head_Closed),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt10),
																	GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt0_Capless_Switch_opt0_Eye_State_Switch_opt11),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, n64_mario_Capless_Head),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, 80, -18, 29, -135),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 121, -35, -80, 18, -29, -135),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 66, 0, 63, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Left_Forearm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, n64_mario_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(1, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Left_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, n64_mario_Left_Hand_Open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, -63, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Forearm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 61, 0, 0, n64_mario_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 71, 0, 0, 0, 0, 1),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, n64_mario_Right_Hand_Open),
																GEO_BRANCH(1, n64_mario_Right_Hand_Peace),
																GEO_BRANCH(1, n64_mario_Right_Hand_Cap),
																GEO_BRANCH(1, n64_mario_Right_Hand_Wing_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, 49, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Left_Leg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, n64_mario_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, n64_mario_Left_Shoe_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Left_Shoe_mesh_layer_5),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 20, 0, -49, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, n64_mario_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Leg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, n64_mario_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 95, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_Right_Shoe_DL_mesh_layer_1),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_Right_Shoe_DL_mesh_layer_5),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt1),
							GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt2),
							GEO_BRANCH(1, n64_mario_B_LoD_Switch_opt0_Cap_State_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, n64_mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, n64_mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, n64_mario_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
